viewer:
  mode: realtime
  viewer_root: third_party/viewer/bin
  model_path: outputs/video_scene_01
  source_path: datasets/processed/video_scene_01
  rendering_width: 1200
  rendering_height: 800
  force_aspect_ratio: false
  load_images: false
  device: 0
  wait_until_close: true
  detached: false
