train:
  scene_name: test_scene
  source_path: datasets/processed/test_scene
  model_output: outputs/test_scene

  active_profile: low_vram 
## 三种模式
  profiles:
    low_vram:
      eval: true
      iterations: 7000
      save_iterations: [3000, 7000]
      test_iterations: [-1]
      quiet: false

      extra_args:
        data_device: cpu
        resolution: 4
        densify_grad_threshold: 0.001
        densification_interval: 200
        densify_until_iter: 3000

    normal:
      eval: true
      iterations: 15000
      save_iterations: [7000, 15000]
      test_iterations: [7000, 15000]
      quiet: false

      extra_args:
        resolution: 2

    fast_preview:
      eval: false
      iterations: 3000
      save_iterations: [1000, 3000]
      test_iterations: [-1]
      quiet: false

      extra_args:
        data_device: cpu
        resolution: 8
        densify_grad_threshold: 0.001
        densification_interval: 250
        densify_until_iter: 1500