train:
  scene_name: liren
  source_path: datasets\processed\liren\fae32ca2370f\gs_input
  model_output: outputs\liren\fae32ca2370f
  active_profile: low_vram
  profiles:
    low_vram:
      eval: true
      iterations: 50000
      save_iterations:
      - 7000
      - 30000
      - 40000
      - 50000
      test_iterations:
      - -1
      checkpoint_iterations:
      - 2000
      - 15000
      - 30000
      - 50000
      start_checkpoint: ''
      resume_from_latest: false
      quiet: false
      extra_args:
        data_device: cuda
        resolution: 1
        densify_grad_threshold: 0.001
        densification_interval: 200
        densify_until_iter: 3000
    normal:
      eval: true
      iterations: 30000
      save_iterations:
      - 7000
      - 30000
      test_iterations:
      - -1
      checkpoint_iterations:
      - 2000
      - 15000
      - 30000
      start_checkpoint: ''
      resume_from_latest: false
      quiet: false
      extra_args:
        data_device: cuda
        resolution: 4
        densify_grad_threshold: 0.001
        densification_interval: 200
        densify_until_iter: 3000
    fast_preview:
      eval: false
      iterations: 7000
      save_iterations:
      - 2000
      - 7000
      test_iterations:
      - -1
      checkpoint_iterations:
      - 2000
      - 7000
      start_checkpoint: ''
      resume_from_latest: false
      quiet: false
      extra_args:
        data_device: cpu
        resolution: 8
        densify_grad_threshold: 0.001
        densification_interval: 300
        densify_until_iter: 1500
