train:
  scene_name: video_scene_01
  source_path: datasets/processed/video_scene_01/gs_input
  model_output: outputs/video_scene_01
  active_profile: fast_preview
  profiles:
    low_vram:
      eval: true
      iterations: 30000
      save_iterations:
      - 7000
      - 30000
      test_iterations:
      - -1
      checkpoint_iterations:
      - 2000
      - 15000
      - 30000
      start_checkpoint: ''
      resume_from_latest: false
      quiet: false
      extra_args:
        data_device: cpu
        resolution: 4
        densify_grad_threshold: 0.001
        densification_interval: 200
        densify_until_iter: 3000
    normal:
      eval: true
      iterations: 30000
      save_iterations:
      - 7000
      - 30000
      test_iterations:
      - -1
      checkpoint_iterations:
      - 2000
      - 15000
      - 30000
      start_checkpoint: ''
      resume_from_latest: false
      quiet: false
      extra_args:
        data_device: cuda
        resolution: 4
        densify_grad_threshold: 0.001
        densification_interval: 200
        densify_until_iter: 3000
    fast_preview:
      eval: true
      iterations: 7000
      save_iterations:
      - 2000
      - 7000
      test_iterations:
      - -1
      checkpoint_iterations:
      - 2000
      - 7000
      start_checkpoint: ''
      resume_from_latest: false
      quiet: false
      extra_args:
        data_device: cpu
        resolution: 8
        densify_grad_threshold: 0.001
        densification_interval: 300
        densify_until_iter: 1500
